In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("tccs.csv", sep=";")
df.head()

,titulo,palavras_chave,nome_autor,nome_orientador,nome_orientador_externo,curso,nivel,tipo_trabalho,ano,data_defesa
0,"""A definir""","cadeia de custódia, processo penal, prova.",BRUNO LUIS CASTRO DA SILVA,WALTER NUNES DA SILVA JUNIOR,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2022.0,6202/09/02 00:00:00.000
1,MÚLTIPLA FILIAÇÃO REGISTRAL: ANÁLISE CONSTITUC...,NÃO INFORMADO.,LORENA NOGUEIRA RÊGO,ERICA VERICIA CANUTO DE OLIVEIRA VERAS,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2015.0,5015/11/25 00:00:00.000
2,O Impacto da Lei de Responsabilidade Fiscal so...,NaN,JULIANA CRISTINA WERNECK,ZIVANILSON TEIXEIRA E SILVA,NaN,CIÊNCIAS ECONÔMICAS,GRADUAÇÃO,MONOGRAFIA,2013.0,3013/12/17 00:00:00.000
3,Avaliação do Programa Agroamigo dos Território...,NaN,KALBY ANDSON ELOI LEITE,ZIVANILSON TEIXEIRA E SILVA,NaN,CIÊNCIAS ECONÔMICAS,GRADUAÇÃO,MONOGRAFIA,2013.0,3013/12/17 00:00:00.000
4,A EXIGIBILIDADE DA VACINAÇÃO COMO MEDIDA PROFI...,Vacinação; COVID-19; Obrigatoriedade; Atletas ...,DIEGO ALBERTO FARIAS DANTAS,DIOGO PIGNATARO DE OLIVEIRA,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2022.0,2202/12/21 00:00:00.000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86827 entries, 0 to 86826
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   titulo                   84982 non-null  object
 1   palavras_chave           40301 non-null  object
 2   nome_autor               86827 non-null  object
 3   nome_orientador          79189 non-null  object
 4   nome_orientador_externo  7630 non-null   object
 5   curso                    86827 non-null  object
 6   nivel                    86827 non-null  object
 7   tipo_trabalho            67134 non-null  object
 8   ano                      86827 non-null  float64
 9   data_defesa              86827 non-null  object
dtypes: float64(1), object(9)
memory usage: 6.6+ MB

In [5]:
df = df.dropna(subset=['titulo'])

In [6]:
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84982 entries, 0 to 86826
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   titulo                   84982 non-null  object
 1   palavras_chave           40300 non-null  object
 2   nome_autor               84982 non-null  object
 3   nome_orientador          77344 non-null  object
 4   nome_orientador_externo  7630 non-null   object
 5   curso                    84982 non-null  object
 6   nivel                    84982 non-null  object
 7   tipo_trabalho            67134 non-null  object
 8   ano                      84982 non-null  float64
 9   data_defesa              84982 non-null  object
dtypes: float64(1), object(9)
memory usage: 7.1+ MB

In [9]:
df[df['titulo'].str.contains("a definir", case=False, na=False)]
#df['titulo'].str.contains("a definir", case=False, na=False).value_counts()

,titulo,palavras_chave,nome_autor,nome_orientador,nome_orientador_externo,curso,nivel,tipo_trabalho,ano,data_defesa
0,"""A definir""","cadeia de custódia, processo penal, prova.",BRUNO LUIS CASTRO DA SILVA,WALTER NUNES DA SILVA JUNIOR,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2022.0,6202/09/02 00:00:00.000
17142,"""A definir""",Sanções econômicas; Evasão; Análise Econômica ...,BRUNO HENRIQUE MACEDO DE MEDEIROS,OTACILIO DOS SANTOS SILVEIRA NETO,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2022.0,2022/07/28 00:00:00.000
21498,A DEFINIR,"Public transparency, Accountability, State-own...",JOSÉ LUIZ MOREIRA REBOUÇAS,OTACILIO DOS SANTOS SILVEIRA NETO,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2021/12/31 00:00:00.000
21502,A DEFINIR,"Transparência pública, Accountability, Lei das...",JOSÉ LUIZ MOREIRA REBOUÇAS,OTACILIO DOS SANTOS SILVEIRA NETO,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2021/12/31 00:00:00.000
31693,A DEFINIR,NaN,FERNANDO HENRIQUE TARGINO,YARA MARIA PEREIRA GURGEL,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2020/04/20 00:00:00.000
31694,A DEFINIR,NaN,JOSÉ DE ANCHIETA CRUZ NETO,YARA MARIA PEREIRA GURGEL,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2020/04/20 00:00:00.000
31695,A DEFINIR,NaN,CARLOS ANDRÉ CORREIA LIMA MORENO,YARA MARIA PEREIRA GURGEL,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2020/04/20 00:00:00.000
31700,A DEFINIR,Palavras-chave: direito fundamental à saúde me...,CAMILLA AMANDA AIRES DE MEDEIROS,YARA MARIA PEREIRA GURGEL,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2020/04/20 00:00:00.000
31701,AINDA A DEFINIR,LABOR COMPLIANCE. PREVENTION. LABOR ACTIONS. M...,STEFFISSON OLIVEIRA DA CRUZ,YARA MARIA PEREIRA GURGEL,NaN,DIREITO,GRADUAÇÃO,MONOGRAFIA,2020.0,2020/04/20 00:00:00.000
55617,A definir,NaN,JOSÉ WILSON DA SILVA SANTOS,HIPOLITO VIRGILIO MAGALHAES JUNIOR,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2016/06/06 00:00:00.000
59436,Título a definir,Síndrome de Down. Leitura. Escrita.,SÉRGIO SILVESTRE BORGES,MARIA DE JESUS GONCALVES,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59440,Título a definir,Respiração oral. Deglutição. Crianças. Mastiga...,MARIA WANESSA NUNES RIBEIRO,JOSELI SOARES BRAZOROTTO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59441,Título a definir,Docentes. Autoavaliação. Voz. Qualidade de vida.,PATRÍCIA BRIANNE DA COSTA PENHA,LOURDES BERNADETE ROCHA DE SOUZA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59443,Título a definir,TANU. Emissões Otoacústicas. Emissões Otoac...,BIANCA FREIRE DE FREITAS,FABIANA CRISTINA MENDONCA DE ARAUJO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59447,Título a definir,"Comunicação, Biblioterapia, Hospital, Fonoa...",VICTOR VASCONCELOS BARROS,MARIA DE JESUS GONCALVES,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59450,Título a definir,Mastigação. Crianças. Oclusão. Promoção. Preve...,FLAVIANA DE SOUZA CARDOSO,RENATA VEIGA ANDERSEN CAVALCANTI,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59451,Título a definir,Autismo. Comunicação alternativa. Transtorno d...,AMANDA FERNANDES DA CUNHA,MARIA DE JESUS GONCALVES,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59457,Título a definir,Hábitos; Saúde Bucal; Crianças; Escolares,PATRICK MACEDO BEZERRA,KARINNA VERISSIMO MEIRA TAVEIRA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59458,Título a definir,Voz. Autoavaliação. Qualidade Vocal. Fonaç...,HEITOR LINCOLN CANUTO DE ALMEIDA,LOURDES BERNADETE ROCHA DE SOUZA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59460,Título a definir,Conhecimento. Triagem Neonatal. Mães. Gestantes.,WALBIA RADIMILA OLIVEIRA DO NASCIMENTO,FABIANA CRISTINA MENDONCA DE ARAUJO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59461,Título a definir,"Voz, Obesidade, Pescoço, Fonação, Fonoaudiologia.",GABRIELA DA SILVA ROCHA,LOURDES BERNADETE ROCHA DE SOUZA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59462,Título a definir,Prótese dentária. Sistema estomatognático. Deg...,ANA LUIZA OLIVEIRA DA SILVA,RENATA VEIGA ANDERSEN CAVALCANTI,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59467,Título a definir,Auxiliares de Audição. Implante Coclear. Crian...,ANGELA ROSANNE SANTOS DE OLIVEIRA,JOSELI SOARES BRAZOROTTO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59469,Título a definir,Respiração bucal. Criança.,MARIA BEATRIZ MEDEIROS DE ARAÚJO,KARINNA VERISSIMO MEIRA TAVEIRA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59470,Título a definir,Audição. Triagem Neonatal. Perda auditiva. Dia...,ANNA PAULA DIONIZIO DA SILVA CAMPELO,FABIANA CRISTINA MENDONCA DE ARAUJO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59475,Título a definir,Triagem neonatal. Perda auditiva. Emissões oto...,MONYKA FERREIRA BORGES,FABIANA CRISTINA MENDONCA DE ARAUJO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59479,Título a definir,Qualidade vocal. Fonoaudiologia. Cavidade oral,CAMILLA MANUELA BARBOSA DE OLIVEIRA,LOURDES BERNADETE ROCHA DE SOUZA,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MEMORIAL,2015.0,2015/11/27 00:00:00.000
59480,Título a definir,Lesão subcortical. Distúrbio de linguagem.,JULIANE MAYARA BORGES FERNANDES,MARIA DE JESUS GONCALVES,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59483,Título a definir,"Prótese dentária, Padrão Mastigatório, Eficiên...",SARAH BEATRIZ FREIRE LIMA,RENATA VEIGA ANDERSEN CAVALCANTI,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
59489,Título a definir,"Criança, Deficiência auditiva, Família, Inte...",GABRIELLA DE FRANÇA ROCHA,JOSELI SOARES BRAZOROTTO,NaN,FONOAUDIOLOGIA,GRADUAÇÃO,MONOGRAFIA,2015.0,2015/11/27 00:00:00.000
65904,A DEFINIR,NaN,ALEXANDRE SILVA DE OLIVEIRA,RONALDO DE ANDRADE MARTINS,NaN,ENGENHARIA ELÉTRICA,GRADUAÇÃO,MONOGRAFIA,2014.0,2014/11/04 00:00:00.000
66016,A Definir,"Rádio Cognitivo, Sensoriamento Espectral, Cicl...",PEDRO THIAGO VALERIO DE SOUZA,LUIZ FELIPE DE QUEIROZ SILVEIRA,NaN,ENGENHARIA ELÉTRICA,GRADUAÇÃO,MONOGRAFIA,2014.0,2014/10/22 00:00:00.000
66145,A definir,NaN,FRANCISCO ALAN DA SILVA MONTEIRO,RONALDO DE ANDRADE MARTINS,NaN,ENGENHARIA ELÉTRICA,GRADUAÇÃO,MONOGRAFIA,2014.0,2014/10/16 00:00:00.000
66162,A definir,NaN,EDER TIAGO DA SILVA PINHEIRO,RONALDO DE ANDRADE MARTINS,NaN,ENGENHARIA ELÉTRICA,GRADUAÇÃO,MONOGRAFIA,2014.0,2014/10/16 00:00:00.000
69265,SIMPLES NACIONAL E LUCRO PRESUMIDO: UM ESTUDO ...,NaN,LUCILIO BEZERRA DE MEDEIROS,SOCRATES DANTAS LOPES,NaN,ESPECIALIZAÇÃO EM FINANÇAS CORPORATIVAS,LATO SENSU,MONOGRAFIA,2013.0,2013/12/30 00:00:00.000
69291,SIMPLES NACIONAL E LUCRO PRESUMIDO: UM ESTUDO ...,NaN,ALBANI SILVA DE OLIVEIRA,SOCRATES DANTAS LOPES,NaN,ESPECIALIZAÇÃO EM FINANÇAS CORPORATIVAS,LATO SENSU,MONOGRAFIA,2013.0,2013/12/30 00:00:00.000
81029,A definir TCC II,NaN,RONI TETEO PESSOA,FRANCINETE DE LIMA,NaN,ENGENHARIA ELÉTRICA,GRADUAÇÃO,MONOGRAFIA,2010.0,2010/08/06 00:00:00.000